# golangci-lint configuration for Smart-ID Go Client

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .git

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    enable-all: true
    disable:
      - fieldalignment
      - shadow

  gocyclo:
    min-complexity: 15

  gofmt:
    simplify: true

  goimports:
    local-prefixes: github.com/PaymentSyst/smart-id-client

  goconst:
    min-len: 3
    min-occurrences: 3
    ignore-tests: true

  funlen:
    lines: 100
    statements: 50

  lll:
    line-length: 120
    tab-width: 4

  misspell:
    locale: US

  revive:
    min-confidence: 0.8
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unreachable-code

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - revive
    - funlen
    - lll
    - gosec

  disable:
    - gochecknoglobals
    - godot
    - godox
    - goerr113
    - gofumpt
    - goheader
    - gomodguard
    - interfacer
    - maligned
    - nestif
    - prealloc
    - scopelint
    - testpackage
    - wsl

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst

    # Exclude lll issues for long lines with go:generate
    - linters:
        - lll
      source: "^//go:generate "

    # Allow unused parameters in interface implementations
    - text: "`.*` is unused"
      linters:
        - unused
      path: .*\.go

  max-same-issues: 0
  max-issues-per-linter: 0
  exclude-use-default: true
  new: false
  fix: false
